# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'carsalesDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  
  # Pods for carsalesDemo

  target 'carsalesDemoTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Quick', '1.3.2'
  pod 'Nimble', '8.0.2'
  end

  target 'carsalesDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
