# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'carsalesDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  # Pods for carsalesDemo

  target 'carsalesDemoTests' do
    inherit! :search_paths
    # Pods for testing
pod 'Quick'
    pod 'Nimble'
  end

  target 'carsalesDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
